# Generated by Django 4.2.10 on 2024-06-24 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nasa_image_gallery', '0002_alter_favourite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favourite',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'title', 'description', 'image_url', 'date', 'comment')},
        ),
    ]
